//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kriclick.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int StateId { get; set; }
        public string StateName { get; set; }
        public string Abbreviation { get; set; }
        public Nullable<short> CountryId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
