//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kriclick.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReview
    {
        public long UserReviewId { get; set; }
        public Nullable<long> UserProfileId { get; set; }
        public decimal Rating { get; set; }
        public string Title { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
